CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY,
    login VARCHAR DEFAULT NULL,
    password VARCHAR DEFAULT NULL,
    firstname VARCHAR DEFAULT NULL,
    lastname VARCHAR DEFAULT NULL,
    email VARCHAR DEFAULT NULL,
    phone_nb VARCHAR DEFAULT NULL
);